// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.Infrastructure.Database;

#nullable disable

namespace Payments.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303145208_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payments.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionCode")
                        .HasColumnType("text")
                        .HasColumnName("action_code");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovalCode")
                        .HasColumnType("text")
                        .HasColumnName("approval_code");

                    b.Property<long?>("ApprovedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("approved_amount");

                    b.Property<string>("BankCountryCode")
                        .HasColumnType("text")
                        .HasColumnName("bank_country_code");

                    b.Property<string>("BankCountryName")
                        .HasColumnType("text")
                        .HasColumnName("bank_country_name");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("CardholderName")
                        .HasColumnType("text")
                        .HasColumnName("cardholder_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<long?>("DepositedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("deposited_amount");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Expiration")
                        .HasColumnType("text")
                        .HasColumnName("expiration");

                    b.Property<long?>("FeeAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_amount");

                    b.Property<string>("GatewayOrderId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_order_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MaskedPan")
                        .HasColumnType("text")
                        .HasColumnName("masked_pan");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("order_status");

                    b.Property<string>("PaymentState")
                        .HasColumnType("text")
                        .HasColumnName("payment_state");

                    b.Property<string>("PaymentSystem")
                        .HasColumnType("text")
                        .HasColumnName("payment_system");

                    b.Property<string>("PaymentWay")
                        .HasColumnType("text")
                        .HasColumnName("payment_way");

                    b.Property<long?>("RefundedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("refunded_amount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("GatewayOrderId")
                        .HasDatabaseName("ix_payments_gateway_order_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_idempotency_key");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_order_number");

                    b.ToTable("payments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
